version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/restart.sh
      runas: root
      timeout: 60
